/*
 * File: app/store/Tasks.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Tasks', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.ModelTask'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.ModelTask',
        storeId: 'Tasks',
        proxy: {
            type: 'ajax',
            url: 'http://66.177.246.44/TSP/api/Task',
            reader: {
                type: 'json'
            }
        }
    }
});