/*
 * File: app/view/TaskForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaskForm', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'TaskForm',
        items: [
            {
                xtype: 'textfield',
                label: 'ID',
                name: 'ID'
            },
            {
                xtype: 'textfield',
                label: 'Task ID',
                name: 'TicklerID'
            },
            {
                xtype: 'textfield',
                label: 'Due Date',
                name: 'DueDate'
            },
            {
                xtype: 'textfield',
                label: 'Type',
                name: 'Type'
            },
            {
                xtype: 'panel',
                margin: '6px',
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        action: 'save',
                        ui: 'confirm',
                        width: 135,
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        action: 'delete',
                        ui: 'decline',
                        width: 116,
                        text: 'Delete'
                    }
                ]
            }
        ]
    }

});