/*
 * File: app/model/ModelTask.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ModelTask', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'ID',
                allowNull: false,
                type: 'int'
            },
            {
                name: 'TicklerID'
            },
            {
                name: 'DueDate',
                allowNull: false,
                type: 'date'
            },
            {
                name: 'AssignedTo'
            },
            {
                name: 'SubAssignedTo'
            },
            {
                name: 'CreatedBy'
            },
            {
                name: 'Type'
            },
            {
                name: 'Description'
            },
            {
                name: 'ListID'
            },
            {
                name: 'Completed'
            },
            {
                name: 'Resolution'
            },
            {
                name: 'StartTime'
            },
            {
                name: 'EndTime'
            }
        ],
        proxy: {
            type: 'rest',
            url: 'http://66.177.246.44/TSP/api/Task'
        }
    }
});